### ISSUE TITLE
Tests failed during Debian packaging

### ISSUE THREAD

**Issue by balasankarc** [stevehodgkiss/generator_spec#33]
Hi,
I am packaging generator_spec for debian and have hit a problem. As a part of packaging, the tests are automatically run. But, I got one failure while running the tests

Failures:
  1) GeneratorSpec::Matcher::File#matches? with no contains throws :failure if it doesnt exist
     Failure/Error: expect {
       expected :failure to be thrown, got nothing
     # ./spec/generator_spec/matcher_spec.rb:71:in `block (4 levels) in module:Matcher'

Finished in 0.11725 seconds
31 examples, 1 failure

As I am a novice in Ruby programming, I don't know what to do. Can you help me fix this?

**Comment by prahal** [comment]
I can reproduce it with the Debian gem2deb tool. Gem2deb generator_spec.
gem2deb extract the gem. Running `rake spec` from inside the gem sources I can also reproduce.
Nowadays I get 6 errors. 
```
rspec ./spec/generator_spec/matcher_spec.rb:83 # GeneratorSpec::Matcher::File#matches? with no contains throws :failure if it doesnt exist
rspec ./spec/generator_spec/matcher_spec.rb:129 # GeneratorSpec::Matcher::Migration#matches? with no contains throws :failure if it doesnt exist
rspec ./spec/generator_spec/matcher_spec.rb:226 # GeneratorSpec::Matcher::Directory#matches? with a directory name throws :failure if it doesnt exist
rspec ./spec/generator_spec/matcher_spec.rb:254 # GeneratorSpec::Matcher::Directory#matches? with a directory object throws :failure if it doesnt exist
rspec ./spec/generator_spec/matcher_spec.rb:272 # GeneratorSpec::Matcher::Directory#matches? #no_file doesnt throw if the file exist
rspec ./spec/generator_spec/matcher_spec.rb:306 # GeneratorSpec::Matcher::Root#matches? returns false on failures
```
From a debug session ./spec/generator_spec/matcher_spec.rb uses as testdir TMP_ROO, ie Dir.tmpdir which here ends up as /tmp.
Obviously the before(:each) examples fail to delete this directory as it misses the permissions (luckily).
I believe the tests fail here as I do not run them as root (ie /tmp is not deleted before each test).

A short test case is in an irb session:
```
require 'tmpdir'
puts Dir.tmpdir
```
